version: "3.8"

services:
  db:
    image: postgres:15
    container_name: jktech-postgres
    environment:
      POSTGRES_DB: book_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Badshahkhan@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: jktech-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://localhost:8000
    container_name: jktech-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend


volumes:
  postgres_data:
